name: Upload Node.js 10 and 12 tool cache
on: workflow_dispatch
jobs:
  upload_tool_cache:
    runs-on: self-hosted
    steps:    
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Python 3.7              # may not need
        uses: actions/setup-python@v3
        with:
          python-version: 3.7.x
      - name: Setup Python 3.10             # may not need
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x
      - name: Setup Node 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'            # need to select our distribution
          java-version: '17'
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
