name: RHEL 7.9 Tool Cache
on: workflow_dispatch
jobs:
  build_tool_cache:
    runs-on: rhel-79-home
    steps:    
      - name: Clear any existing tool cache
        run: |
          rm -rf "${{ runner.tool_cache }}" 
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'            # need to select our distribution
          java-version: '17'
      - name: Setup Java 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'            # need to select our distribution
          java-version: '16'
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'            # need to select our distribution
          java-version: '11'
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'            # need to select our distribution
          java-version: '8'           
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
